### ISSUE TITLE
Importing from envirophat fails with a TypeError

### ISSUE THREAD

**Issue by glitchcrab** [pimoroni/enviro-phat#19]
When attempting to import from envirophat I get the following (note that this worked when I last tried it, maybe 3-4 months previously):

```
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from envirophat import weather
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/envirophat/__init__.py", line 12, in <module>
    light = tcs3472(bus)
  File "/usr/lib/python3/dist-packages/envirophat/tcs3472.py", line 35, in __init__
    raise TypeError("Object given for i2c_bus must implement read_word_data and write_byte_data")
TypeError: Object given for i2c_bus must implement read_word_data and write_byte_data
```

Some details about the system:

```
python3-envirophat:
  Installed: 0.0.6
  Candidate: 0.0.6
  Version table:
 *** 0.0.6 0
        500 http://archive.raspberrypi.org/debian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status
```

```
root@pi-zero-1:~# lsmod | grep i2c
i2c_bcm2708             5740  0 
i2c_dev                 6578  0
```

```
root@pi-zero-1:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --
```

I'm not really sure what else I can do to debug this; any suggestions are welcome!

**Comment by Gadgetoid** [comment]
Can you grab details on the `smbus` package?

And potentially run:

```
python3 -c "import smbus;bus = smbus.SMBus(1);print(dir(bus))"
```

**Comment by glitchcrab** [comment]
Sure!

```root@pi-zero-1:~# apt-cache policy python3-smbus
python3-smbus:
  Installed: 3.1.1+svn-2
  Candidate: 3.1.1+svn-2
  Version table:
 *** 3.1.1+svn-2 0
        500 http://archive.raspberrypi.org/debian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status
```

```
root@pi-zero-1:~# python3 -c "import smbus;bus = smbus.SMBus(1);print(dir(bus))"
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_set_addr', 'addr', 'fd', 'read_byte_data', 'write_byte_data']
```

**Comment by Gadgetoid** [comment]
That's.... weird!

For comparison, here's the output when I run the same command:

```
pi@phildev:~ $ python3 -c "import smbus;bus = smbus.SMBus(1);print(dir(bus))"
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__',
 '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__',
 '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__'
, '__str__', '__subclasshook__', 'block_process_call', 'close', 'open', 'pec', 
'process_call', 'read_block_data', 'read_byte', 'read_byte_data',
 'read_i2c_block_data', 'read_word_data', 'write_block_data', 'write_byte',
 'write_byte_data', 'write_i2c_block_data', 'write_quick', 'write_word_data']
```

Note the abundance of read/write helper methods at the bottom. These appear to be missing for you. I'm not sure why. I have the same Python version and the same version of `python3-smbus`.

My best guess is that you're using a version built from source via pip that somehow doesn't include these methods, or doesn't bind them. Try:

```
sudo pip uninstall python3-smbus
sudo apt-get install python3-smbus
```

**Comment by glitchcrab** [comment]
OK, this gets weirder! I hadn't installed through pip so that didn't help, but I did try the following:

python2 version:
```
root@pi-zero-1:~# apt-cache policy python-smbus
python-smbus:
  Installed: 3.1.1+svn-2
  Candidate: 3.1.1+svn-2
  Version table:
 *** 3.1.1+svn-2 0
        500 http://archive.raspberrypi.org/debian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status
     3.1.1-1 0
        500 http://mirrordirector.raspbian.org/raspbian/ jessie/main armhf Packages
```
python3 version:
```
root@pi-zero-1:~# apt-cache policy python3-smbus
python3-smbus:
  Installed: 3.1.1+svn-2
  Candidate: 3.1.1+svn-2
  Version table:
 *** 3.1.1+svn-2 0
        500 http://archive.raspberrypi.org/debian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status
```
Then the same commandline test with both versions of python:

python2:
```
root@pi-zero-1:~# python -c "import smbus;bus = smbus.SMBus(1);print(dir(bus))"
['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'block_process_call', 'close', 'open', 'pec', 'process_call', 'read_block_data', 'read_byte', 'read_byte_data', 'read_i2c_block_data', 'read_word_data', 'write_block_data', 'write_byte', 'write_byte_data', 'write_i2c_block_data', 'write_quick', 'write_word_data']
```
python3:
```
root@pi-zero-1:~# python3 -c "import smbus;bus = smbus.SMBus(1);print(dir(bus))"
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_set_addr', 'addr', 'fd', 'read_byte_data', 'write_byte_data']
```

So both packages are installed through apt but only the python2 version seems to offer the extra methods, even though the apt package version numbers are identical.

**Comment by glitchcrab** [comment]
@Gadgetoid any luck with this at all?

**Comment by RogueM** [comment]
are you simply logged as root (is there a particular reason why?) or in what way is your system custom?

either way, while the smbus output is weird, the fact you get no trace with `i2cdetect` seems to indicate that is a byproduct rather than main issue. For troubleshooting sake, are we saying the Enviro pHAT works under Python 2?

**Comment by glitchcrab** [comment]
@RogueM I'm just logged in as root at that point to try and remove any potential permissions issues. The same thing happens using an unprivileged user (who is member of the i2c group too).

Yes, it would seem that it only works correctly for Python2.

**Comment by glitchcrab** [comment]
@Gadgetoid @RogueM any joy with this at all? It's rather holding me up with a project :( In the meantime I'm going to set up my spare Zero to see if I can replicate on a fresh Raspbian install.

**Comment by RogueM** [comment]
I don't really have any constructive suggestions - your smbus3 package for some reason seems to only be partially functioning, though as I noted you should still get i2cdetect expected output regardless, so it's hard to pinpoint what part of your system is not playing ball.

so, yes, a fresh install to confirm this is a freak occurrence somehow rooted in that particular configuration would probably be my first attempt at figuring it out.

**Comment by glitchcrab** [comment]
@RogueM @Gadgetoid it appears a fresh Zero/OS has helped:

```
root@raspberrypi:/home/shw# python3 -c "import smbus;bus = smbus.SMBus(1);print(dir(bus))"
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'block_process_call', 'close', 'open', 'pec', 'process_call', 'read_block_data', 'read_byte', 'read_byte_data', 'read_i2c_block_data', 'read_word_data', 'write_block_data', 'write_byte', 'write_byte_data', 'write_i2c_block_data', 'write_quick', 'write_word_data']
```

Does that look as expected?

**Comment by Gadgetoid** [comment]
Sorry for the delay, that looks more sensible! Presumably you're up and running now, so I'm going to close this issue.
